python3 instead of python its work for me
Hi and thanks Tacombel, i change python3 instead of python its work for me, in line 29 and 37.
My example in RPi4 on Ubuntu 22.04 LTS
ubuntu@ubuntu:/SCPrime/scprime_price_check-0.5$ python scprime_price_check.py
  File "scprime_price_check.py", line 20
    print(f'Target price {target_scp_price}', flush=True)
                                           ^
SyntaxError: invalid syntax
ubuntu@ubuntu:/SCPrime/scprime_price_check-0.5$ python3 scprime_price_check.py
Status of Primary Provider= 1 :: 0=Offline :: 1=Online :: 2=Error
Reference price on Primary Provider = 10.3622379325272
Target price 10.3
Current price 10.3
No change
ubuntu@ubuntu:/SCPrime/scprime_price_check-0.5$ sudo su
root@ubuntu:/SCPrime/scprime_price_check-0.5# python scprime_price_check.py
  File "scprime_price_check.py", line 20
    print(f'Target price {target_scp_price}', flush=True)
                                           ^
SyntaxError: invalid syntax
root@ubuntu:/SCPrime/scprime_price_check-0.5# python3 scprime_price_check.py
Status of Primary Provider= 1 :: 0=Offline :: 1=Online :: 2=Error
Reference price on Primary Provider = 10.3622379325272
Target price 10.3
Current price 10.3
No change
root@ubuntu:/SCPrime/scprime_price_check-0.5# crontab -e
crontab: installing new crontab
root@ubuntu:/SCPrime/scprime_price_check-0.5# journalctl -n100|grep checkprice-cron
root@ubuntu:/SCPrime/scprime_price_check-0.5# 
Thank you!!!!